### PR TITLE
fixed missing img error, fixed dotdotdot not working correctly (for new releases)

### PR DESCRIPTION
**Pull request by Jbrunn**
check out the code that generates the new releases HTML. I updated it, put in some comments and fixed dotdotdot. See if you can figure out how/why it works now.

### CODE REVIEW

**Comment by Jbrunn** [comment]
Also check if release data is null. There was a movie causing this error after the server fix. Updated the menu so that it will lose once a menu item is selected.

**Comment by SuragSheth** [comment]
Wow. You have done a crazy amount of work! I am going to go through all of the lines of code and see what changes you have made right now and comment on the things that I don't understand, and check if the release data is null.  Tomorrow I will work on getting the charts and graphs made from the s & e analysis, add light box for the images, get the social media buttons working and sharing what I want. I see you have defined the height of the boxes and im guessing that why dotdotdot is not working but I will look more into that as well as adding the configurations for it. I had gotten some of the genre id's and added them to the code but i think you covered everything.

**Comment by SuragSheth** [comment]
This is great, I need to make sure to understand all of the changes however, but I like how git has the option to look at the changes between the updates. Have only used bit bucket before and we didn't even use it to its potential then.

**Comment by SuragSheth** [comment]
and re-organize the files like your originally suggested.

**Comment by Jbrunn** [comment]
To be fair, I didn't do too much. I just know where changes need to be
made. To be clear, dotdotdot is working, but, only for new releases. I
could have fixed it for both, but then you wouldn't learn anything! The CSS
of .movieDesc helps style dotdotdot, but isn't the reason that it is
working hint: look through the changes of where the function is being
called, as well as the html structure of a movie. We should hangout
tomorrow when you get in, and I can screenshare my changes and you can ask
questions.

Jeremy

**Comment by SuragSheth** [comment]
sounds good. We are leaving to the office right now in 10. Then I will spend and hour looking over everything and then I will hit you up on hangout. Thanks!

**Pull request merged**
